// Generated by https://quicktype.io

import type { ClaseResponse } from "./clase.response";


export interface AulaResponse {
    total: number;
    pages: number;
    aulas: Aula[];
}

export interface Aula {
    id: string;
    name: string;
    description: string;
    capacity: number;
    state: state;
    clase: ClaseResponse[];
}

export type state = "available" | "maintenance" | "busy";