// Generated by https://quicktype.io

export interface AulaResponse {
    total: number;
    pages: number;
    aulas: Aula[];
}

export interface Aula {
    id: string;
    name: string;
    description: string;
    capacity: number;
    estado: Estado;
    clase: any[];
}

export interface Estado {
    id: number;
    name: string;
}